### ISSUE TITLE
[Feature]: S3connection credential support SecretClass and SecretClass scope

### ISSUE THREAD

**Issue by whg517** [zncdatadev/commons-operator#38]
### Summary 💡

Use SecretClass to provide authentication secrets for S3connection.

### Examples 🌈

Current:

```yaml
apiVersion: zncdata.dev/v1alpha1
kind: S3Connection
metadata:
  name: s3connection-sample
spec:
  credential:
    existSecret: s3connection-sample-root-1

```

New

```yaml
apiVersion: zncdata.dev/v1alpha1
kind: S3Connection
metadata:
  name: s3connection-sample
spec:
  credential:
    secretClass: s3connection-sample
    scope:
      # node: true
      pod: true
      # services: 
      #   - foo
      #   - bar

```
