### ISSUE TITLE
[Bug]: could not update csv when make bundle

### ISSUE THREAD

**Issue by whg517** [zncdatadev/commons-operator#61]
### Describe the bug

Through testing, this is a bug in operator-sdk when generating bundles, and there is no way to fix it from the current project, and there is no feedback in the community.

## Description

When the `make bundle` is executed, the `generate kustomize manifests -q` command is executed to generate a csv file. During this process, the api directory of the current project is searched and CRD information generated by the api definition in the directory is updated to the csv.

eg: `config/manifests/bases/commons-operator.clusterserviceversion.yaml`

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    categories: Big Data
  name: commons-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: AuthenticationClass is the Schema for the authenticationclasses
        API
      displayName: Authentication Class
      kind: AuthenticationClass
      name: authenticationclasses.authentication.zncdata.dev
      version: v1alpha1
    - description: S3Bucket is the Schema for the s3buckets API
      displayName: S3 Bucket
      kind: S3Bucket
      name: s3buckets.s3.zncdata.dev
      version: v1alpha1
    - description: S3Connection is the Schema for the s3connections API
      displayName: S3 Connection
      kind: S3Connection
      name: s3connections.s3.zncdata.dev
      version: v1alpha1
  description: zncdatadev commons operator
  displayName: commons operator
```

`customresourcedefinitions` content is below the make bundles according to API directory content generation.

Because the api structure in commons-operator is already extracted into operator-go, when `make bundle`, the operator runs a warning and does not dynamically update the csv based on the contents of the api directory

```text
operator-sdk generate kustomize manifests -q
WARN[0000] Skipping definitions parsing: APIs root dir "api" does not exist 
```

Looking at the help command, we see that operator-sdk has a parameter `--apis-dir` that specifies the api directory

*But no matter what value you pass, it will only continue concatenating downward relative to the current project directory location, unless you use ../.*

However, the location of the package in operator-go and the current project and path are uncertain.

## sulotion-1

When `make bundle`, use go mod vendor to download the dependency to the vendor directory under the current project, and specify the operator-sdk api directory in the vendor through `apis-dir`. Delete vendor after use.

```diff
 .PHONY: bundle
 bundle: manifests kustomize operator-sdk ## Generate bundle manifests and metadata, then validate generated files.
-       $(OPERATOR_SDK) generate kustomize manifests -q
+       go mod vendor -o .vendor        # use .vendor to avoid conflict with the project's vendor directory
+       $(OPERATOR_SDK) generate kustomize manifests -q --apis-dir=.vendor/github.com/zncdatadev/operator-go/pkg/apis/
        cd config/manager && $(KUSTOMIZE) edit set image controller=$(IMG)
        $(KUSTOMIZE) build config/manifests | $(OPERATOR_SDK) generate bundle $(BUNDLE_GEN_FLAGS)
        $(OPERATOR_SDK) bundle validate ./bundle --select-optional suite=operatorframework --optional-values=k8s-version=1.26
+       rm -rf .vendor
```

When using go mod vendor, only the direct dependencies will be downloaded, so in order to download the contents of the api directory, you need to import the api module in the project logic code, even if we don't actually call the logic in the api right now.

```diff
--- a/cmd/main.go
+++ b/cmd/main.go
@@ -37,7 +37,13 @@ import (
 
        "github.com/zncdatadev/commons-operator/internal/controller/pod_enrichment"
        "github.com/zncdatadev/commons-operator/internal/controller/restart"
+
        //+kubebuilder:scaffold:imports
+
+       // Now we need to import the constants package to fix olm bundle generate error
+       // later refactoring with constants feature, we will use it.
+       _ "github.com/zncdatadev/operator-go/pkg/apis/authentication/v1alpha1"
+       _ "github.com/zncdatadev/operator-go/pkg/apis/s3/v1alpha1"
 )
```

### Have you searched existing issues?  🔎

no check

### Reproduction

-

### System Info

```shell
- go 1.23.0
- operator-go 0.9.1
```

### Severity

Blocking usage of operator
